{"hash":"26d421e920ef2750f9c5d22a71ef31b50eb50a59","data":{"post":{"title":"MLflow untrusted dataset XSS","path":"/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/","content":"<h2 id=\"summary\"><a href=\"#summary\" aria-hidden=\"true\" tabindex=\"-1\">Summary</a></h2>\n<p>Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset.</p>\n<h2 id=\"component\"><a href=\"#component\" aria-hidden=\"true\" tabindex=\"-1\">Component</a></h2>\n<p>mlflow</p>\n<h2 id=\"affected-versions\"><a href=\"#affected-versions\" aria-hidden=\"true\" tabindex=\"-1\">Affected versions</a></h2>\n<p>(,2.9.2]</p>\n<h2 id=\"description\"><a href=\"#description\" aria-hidden=\"true\" tabindex=\"-1\">Description</a></h2>\n<p>Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields.</p>\n<h2 id=\"poc\"><a href=\"#poc\" aria-hidden=\"true\" tabindex=\"-1\">PoC</a></h2>\n<p>The following mlflow code would be vulnerable to this issue, when using a Recipe that uses an untrusted dataset -</p>\n<pre><code class=\"language-python\">from mlflow.recipes import Recipe\nfrom mlflow.pyfunc import PyFuncModel\nfrom IPython.core.debugger import set_trace\nregression_recipe = Recipe(profile=\"local\")\n# Run the full recipe\nregression_recipe.run()\n# Inspect the model training results\nregression_recipe.inspect(step=\"train\")\n# Load the trained model\nregression_model_recipe: PyFuncModel = regression_recipe.get_artifact(\"model\")\n</code></pre>\n<h2 id=\"vulnerability-mitigations\"><a href=\"#vulnerability-mitigations\" aria-hidden=\"true\" tabindex=\"-1\">Vulnerability Mitigations</a></h2>\n<p>No mitigations are supplied for this issue</p>\n<h2 id=\"references\"><a href=\"#references\" aria-hidden=\"true\" tabindex=\"-1\">References</a></h2>\n<p><a href=\"https://github.com/mlflow/mlflow/pull/10893\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">Fix PR</a></p>\n","description":"CVE-2024-27133, HIGH, Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset.","date_published":"2024-02-23","xray_id":"JFSA-2024-000631932","vul_id":"CVE-2024-27133","severity":"high","discovered_by":"Uriya Yavnieli","last_updated":"2024-02-23","cvss":null}},"context":{}}